# Generated by Django 4.1.5 on 2023-01-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_message_alter_comments_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="blog.comments",
                verbose_name="Article",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(max_length=1500),
        ),
    ]
